language: node_js
node_js:
  - "0.10"
  - 0.12
  - iojs
  - 4
  - 5
  - 6

notifications:
  email:
    recipients:
      - office@alexanderwallin.com
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0ed18fd9b3e529b3c2cc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
